name: 'Test'
description: 'Test Python'

inputs:
  token:
    description: 'Codecov token'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Build Python
      uses: ./.github/actions/builder

    - name: Test Python
      shell: bash
      run: uv run pytest --cov --cov-branch --cov-report=xml
      if: ${{ always() }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.token }}
        files: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
