repos:
- hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - args:
    - --fix
    id: ruff-check
    stages:
    - pre-push
  - id: ruff-format
    stages:
    - pre-push
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.11
- hooks:
  - id: commitizen
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.3
