name: 'Python code check'
description: 'Run Python code quality tools against code'
inputs:
  working-directory:
    description: 'Directory to run commands from'
    required: true
  path:
    description: 'Path to point to for checks'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Build Python
      uses: ./.github/actions/builder

    - id: ruff
      if: always()
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: uv run ruff check

    - id: ruff-format
      if: always()
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: uv run ruff format --verbose --diff

    - id: ty
      if: always()
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: uv run ty check ${{ inputs.path }}
